# Generated by Django 5.1.4 on 2025-02-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet_info',
            name='question',
            field=models.TextField(default='sdfsdf'),
            preserve_default=False,
        ),
    ]
