# Generated by Django 5.1.4 on 2025-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_planet_info_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagloue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('character_name', models.CharField(max_length=10)),
                ('dialogue', models.TextField()),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_1_branch', models.CharField(max_length=20)),
                ('option_2_branch', models.CharField(max_length=20)),
                ('option_3_branch', models.CharField(max_length=20)),
            ],
        ),
    ]
