# Generated by Django 5.1.4 on 2025-03-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_diagloue'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagloue',
            name='game_over',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagloue',
            name='game_win',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
