# Generated by Django 5.1.4 on 2025-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_diagloue_game_over_diagloue_game_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagloue',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagloue',
            name='option_1_hint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diagloue',
            name='option_2_hint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diagloue',
            name='option_3_hint',
            field=models.TextField(null=True),
        ),
    ]
