# Generated by Django 5.1.4 on 2025-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_diagloue_correct_option_diagloue_option_1_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagloue',
            name='ending_message',
            field=models.TextField(null=True),
        ),
    ]
