# Generated by Django 5.1.4 on 2025-03-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_diagloue_ending_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='savepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_visited', models.JSONField(blank=True, default=[0, 0, 0, 0, 0, 0, 0, 0, 0])),
                ('past_x_position', models.JSONField(blank=True)),
                ('past_y_position', models.JSONField(blank=True)),
                ('time', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('x_pos', models.FloatField(default=0)),
                ('y_pos', models.FloatField(default=0)),
                ('game_won', models.BooleanField(default=False)),
            ],
        ),
    ]
