# Generated by Django 5.1.4 on 2025-03-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_savepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='manner_savepoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('game_won', models.BooleanField(default=False)),
                ('options_choosen', models.JSONField(blank=True)),
                ('choosing_scenario', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='manner_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('save_points', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='space_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('save_points', models.JSONField(blank=True)),
            ],
        ),
    ]
