# Generated by Django 5.1.4 on 2025-03-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_manner_savepoints_manner_users_space_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_savepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('game_won', models.BooleanField(default=False)),
                ('map_draged', models.JSONField(blank=True)),
                ('map_correct', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='map_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('save_points', models.JSONField(blank=True)),
            ],
        ),
    ]
